import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import BottomNav from "../components/bottomnav/BottomNav";
import { SearchLocationProvider } from "../components/search/SearchLocationContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 pb-16 sm:pb-0">
        <SearchLocationProvider>
          <Header />
          <div className="w-full sm:w-full md:max-w-6xl md:mx-auto">
            {children}
          </div>
          <Footer />
          <BottomNav />
        </SearchLocationProvider>
      </body>
    </html>
  );
}
